const app=document.querySelector('#app');
let objects=[],byId=new Map(),byForm=new Map(),history=[],view={type:'home'},engine;
let saved=JSON.parse(localStorage.getItem('liens-saved')||'[]');
const norm=s=>String(s).toLowerCase().trim().replace(/[.?！!]/g,'').replace(/’/g,"'");
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const persist=()=>localStorage.setItem('liens-saved',JSON.stringify(saved));
const savedIds=()=>saved.map(x=>x.id).filter(Boolean);
function shell(content){app.innerHTML=`<div class="shell"><header class="top"><button class="brand" data-home>L<i>i</i>ens</button><div class="top-actions"><button class="icon" aria-label="Vocabulary" data-vocab>▤</button><button class="icon" aria-label="Home" data-home>⌂</button></div></header><main class="main">${content}</main></div>`;bind()}
async function load(){try{let payload=await fetch('data/wordbank/wordbank-index.json').then(r=>r.ok?r.json():Promise.reject());objects=payload.objects;objects.forEach(o=>{byId.set(o.id,o);let a=byForm.get(o.normalized_form)||[];a.push(o);byForm.set(o.normalized_form,a)});engine=new SentenceIntelligence(objects);home()}catch{app.innerHTML='<main class="main"><p class="empty">The local knowledge graph could not load. Serve this folder with a local web server.</p></main>'}}
function home(){view={type:'home'};shell(`<section class="home"><div class="eyebrow">French, in context</div><h1>Every connection is <em>learnable.</em></h1><p class="subtitle">Search any French word, form, or sentence. Follow its connections. Keep what matters.</p><form class="search" id="search"><input autofocus placeholder="Try: sommes or je suis allé à Paris" aria-label="Search French"/><button aria-label="Search">→</button></form><div class="suggestions"><span>Explore</span><button class="chip" data-query="sommes">sommes</button><button class="chip" data-query="je suis allé à Paris">je suis allé à Paris</button><button class="chip" data-query="je vais apprendre le français">je vais apprendre le français</button></div><div class="home-footer">Learn → Explore → Save → Review</div></section>`) }
function resolve(input){let q=norm(input),hits=byForm.get(q)||[],object=hits.find(o=>['word','inflected_form','expression','idiom','collocation','grammar_construction'].includes(o.type_code));if(object)return{type:'object',id:object.id};return input.trim().split(/\s+/).length>1?{type:'sentence',text:input}:{type:'missing',query:input}}
function related(o){return(o.relationships||[]).map(r=>({type:r.type,target:byId.get(r.target)})).filter(x=>x.target)}
function objectPage(v){let o=byId.get(v.id);if(!o)return home();view=v;let d=(o.definitions||[])[0]||{},formOf=related(o).find(x=>x.type==='inflected_form_of'),links=related(o).filter(x=>x.type!=='inflected_form_of'&&x.type!=='member_of_paradigm'),key='object:'+o.id,isSaved=saved.some(x=>x.key===key),label=o.type_code.replace(/_/g,' ');shell(`<section class="page"><button class="back" data-back>← Back</button><div class="type">${esc(label)}${formOf?` · form of ${esc(formOf.target.display_form)}`:''}</div><div class="heading-row"><div><h1 class="word-title">${esc(o.display_form)}</h1><p class="phonetic">${o.ipa?esc(o.ipa):o.features?`${esc(o.features.mood||'')} ${esc(o.features.tense||'')} · ${esc(o.features.person||'')}${o.features.number==='plural'?' plural':o.features.number==='singular'?' singular':''}`:'Local learning object'}</p></div><button class="save ${isSaved?'saved':''}" data-save-object="${esc(o.id)}">${isSaved?'Saved':'＋ Save'}</button></div><p class="meaning">${esc(d.chinese_gloss||'')} <span class="definition">${esc(d.english_gloss||'Core local entry')}</span></p><div class="facts">${o.cefr_level?`<span class="fact">${o.cefr_level}</span>`:''}${o.part_of_speech?`<span class="fact">${esc(o.part_of_speech)}</span>`:''}${o.frequency_per_million?`<span class="fact">frequency ${Math.round(o.frequency_per_million)}/m</span>`:''}<span class="fact">${esc(o.content_status)}</span></div><div class="section"><h2>Learn in context</h2><p class="section-copy">${esc(d.explanation_en||'This core object is resolved locally. A teacher-style explanation can be added as reviewed enrichment without changing its identity.')}</p>${d.chinese_gloss?`<p class="section-copy">${esc(d.explanation_zh||'')}</p>`:''}</div>${links.length?`<div class="section"><h2>Useful connections</h2><div class="collocations">${links.map(x=>`<button class="link-card" data-object="${esc(x.target.id)}"><small>${esc(x.type.replace(/_/g,' '))}</small> ${esc(x.target.display_form)} <span>→</span></button>`).join('')}</div></div>`:''}<div class="section"><h2>Graph identity</h2><p class="section-copy">${esc(o.id)}</p></div></section>`) }
function clickable(id,label,cls='token'){return id?`<button class="${cls}" data-object="${esc(id)}">${esc(label)}</button>`:`<span class="${cls}">${esc(label)}</span>`}
function sentencePage(v){let a=engine.analyze(v.text,savedIds()),key='sentence:'+a.normalizedSentence,isSaved=saved.some(x=>x.key===key);view={...v,analysis:a};let evidence=new Map();[...a.expressions,...a.grammar].forEach(n=>(n.evidence||[]).forEach(i=>{let kinds=evidence.get(i)||[];kinds.push(n.type==='grammar_construction'?'grammar':'expression');evidence.set(i,kinds)}));let grammar=a.grammar,expressions=a.expressions,learning=a.learning;let objectFor=t=>t.objectId||t.lemmaId;let known=learning.reviewCandidateIds.length;let unknown=a.unknownTokens.length;shell(`<section class="page sentence-page"><button class="back" data-back>← Back</button><div class="type">Sentence learning</div><div class="heading-row"><div><h1 class="sentence-title">${esc(a.sentence)}</h1><p class="translation">${unknown?`Local analysis · ${unknown} new item${unknown>1?'s':''}`:'A fully connected local reading.'}</p></div><button class="save ${isSaved?'saved':''}" data-save-sentence="${esc(a.normalizedSentence)}">${isSaved?'Saved':'＋ Save'}</button></div><div class="insight"><div class="label">Why it works this way</div><p>${grammar.length?`${grammar.map(n=>esc(n.label)).join(' · ')} recognised from the sentence structure.`:'Liens resolved the words locally and is keeping the sentence ready for exploration.'}</p></div><div class="section"><h2>Sentence breakdown</h2><div class="tokens sentence-tokens">${a.tokens.map((t,i)=>clickable(objectFor(t),t.surface,`token sentence-token ${(evidence.get(i)||[]).join(' ')}`)).join(' ')}</div>${unknown?`<p class="section-copy">New locally: ${esc(a.unknownTokens.join(', '))}.</p>`:''}</div>${expressions.length?`<div class="section"><h2>Useful connections</h2><div class="collocations">${expressions.map(n=>clickable(n.objectId,n.label,'link-card expression-card')).join('')}</div></div>`:''}${grammar.length?`<div class="section"><h2>Grammar in this sentence</h2><div class="collocations">${grammar.map(n=>clickable(n.objectId,n.label,'link-card grammar-card')).join('')}</div></div>`:''}<div class="section"><h2>Learning opportunities</h2><p class="section-copy">${known} objects recognised · ${expressions.length} expressions · ${grammar.length} grammar constructions · ${a.edges.length} connections.</p><div class="facts"><span class="fact">${learning.newObjectIds.length} new</span><span class="fact">${learning.savedObjectIds.length} saved</span><span class="fact">${learning.reviewCandidateIds.length} review candidates</span><span class="fact">${estimateLevel(a)}</span></div>${learning.reviewCandidateIds.length?`<div class="collocations">${learning.reviewCandidateIds.slice(0,8).map(id=>clickable(id,byId.get(id)?.display_form||id,'link-card')).join('')}</div>`:''}</div></section>`) }
function estimateLevel(a){let levels=a.tokens.map(t=>byId.get(t.lemmaId||t.objectId)?.cefr_level).filter(Boolean),rank={A1:1,A2:2,B1:3,B2:4};return levels.sort((x,y)=>rank[y]-rank[x])[0]||'—'}
function missing(v){view=v;shell(`<section class="page"><button class="back" data-back>← Back</button><div class="type">Local lookup</div><h1 class="sentence-title">${esc(v.query)}</h1><div class="insight"><div class="label">Not in the local graph</div><p>This is not yet a known Language Object. AI enrichment is intentionally disabled in this milestone.</p></div></section>`) }
function vocabulary(){view={type:'vocab'};shell(`<section class="page"><div class="collection-header"><div class="type">Your learning</div><h1>Vocabulary</h1></div><div class="saved-list">${saved.length?saved.map(x=>`<div class="saved-item"><button data-object="${esc(x.id)}"><strong>${esc(x.title)}</strong><span>${esc(x.detail)}</span></button><button class="icon" data-remove="${esc(x.key)}">×</button></div>`).join(''):`<div class="empty">Nothing saved yet. Explore an object or sentence first.</div>`}</div></section>`) }
function render(target){if(target.type==='object')objectPage(target);else if(target.type==='sentence')sentencePage(target);else if(target.type==='vocab')vocabulary();else if(target.type==='missing')missing(target);else home()}
function go(target){history.push(view);render(target)}
function bind(){document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>{history=[];home()});document.querySelectorAll('[data-vocab]').forEach(x=>x.onclick=vocabulary);let f=document.querySelector('#search');if(f)f.onsubmit=e=>{e.preventDefault();go(resolve(f.querySelector('input').value))};document.querySelectorAll('[data-query]').forEach(x=>x.onclick=()=>go(resolve(x.dataset.query)));document.querySelectorAll('[data-object]').forEach(x=>x.onclick=()=>go({type:'object',id:x.dataset.object}));document.querySelectorAll('[data-back]').forEach(x=>x.onclick=()=>{let p=history.pop();p?render(p):home()});document.querySelectorAll('[data-save-object]').forEach(x=>x.onclick=()=>{let o=byId.get(x.dataset.saveObject),key='object:'+o.id,i=saved.findIndex(s=>s.key===key);i>=0?saved.splice(i,1):saved.unshift({key,id:o.id,title:o.display_form,detail:(o.definitions||[])[0]?.english_gloss||o.type_code});persist();render(view)});document.querySelectorAll('[data-save-sentence]').forEach(x=>x.onclick=()=>{let key='sentence:'+x.dataset.saveSentence,i=saved.findIndex(s=>s.key===key);i>=0?saved.splice(i,1):saved.unshift({key,id:'',title:view.text,detail:'Sentence exploration'});persist();render(view)});document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{saved=saved.filter(s=>s.key!==x.dataset.remove);persist();vocabulary()})}
app.innerHTML='<main class="main"><p class="empty">Loading local knowledge graph…</p></main>';load();
