const app=document.querySelector('#app');let navigationStack=[],view={type:'home'},saved=JSON.parse(localStorage.getItem('liens-saved')||'[]'),engine,renderEpoch=0,routeEpoch=0;let objects=[],byId=new Map(),byForm=new Map(),senseOwners=new Map(),autoLearningFailures=new Map(),graphData;
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[.?！!]/g,'').replace(/’/g,"'");const persist=()=>localStorage.setItem('liens-saved',JSON.stringify(saved));const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const showChinese=()=>localStorage.getItem('liens-show-chinese')!=='false';
const chinese=s=>showChinese()&&s?`<span class="chinese">${esc(s)}</span>`:'';
const learningAssist=()=>window.LiensLearningAssist||null;
const aiAssistanceEnabled=()=>Boolean(learningAssist()?.enabled());
const aiProviderReady=()=>Boolean(learningAssist()?.providerReady());
function aiRequest(target,kind,title,context={},language='en'){return {target,kind,title,language,query:context.query||'',context}}
function aiPayload(request){return {targetId:request.target?.id||'',kind:request.kind,title:request.title,language:request.language||'en',query:request.query||'',context:request.context||{}}}
function aiAction(request,label,classes=''){return aiAssistanceEnabled()&&aiProviderReady()?`<button class="${classes}" data-ai-assist='${esc(JSON.stringify(aiPayload(request)))}'>${esc(label)}</button>`:''}
function autoLearningKey(request){return learningAssist()?.keyFor?.(request)||JSON.stringify(aiPayload(request))}
function failureMessage(error){let message=String(error?.message||error||'').toLowerCase();if(message.includes('rate limited')||message.includes('temporarily busy'))return 'Online learning assistance is temporarily busy. Liens will keep the local analysis available.';if(message.includes('took too long'))return 'Online learning assistance took too long. The local graph remains available.';return 'Learning guidance is temporarily unavailable. The local graph remains available.'}
function rememberAutoFailure(request,error){autoLearningFailures.set(autoLearningKey(request),failureMessage(error))}
const referenceLanguages=()=>showChinese()?['zh-Hans']:[];
function languageLabel(language){try{return new Intl.DisplayNames(['en'],{type:'language'}).of(language)||language}catch{return language}}
function referenceLearningSlots(target,kind,title,context={},options={}){return referenceLanguages().map(language=>aiLearningSlot(aiRequest(target,kind,title,context,language),{...options,emptyMessage:`Preparing ${languageLabel(language)} guidance…`})).join('')}
function aiFollowUp(request){let assist=learningAssist();if(!assist)return '';let label=request.target?.display_form||request.title||'this topic',items=[
  {kind:'examples',label:'Give another example',title:`Examples for ${label}`},
  {kind:'memory_tip',label:'Give a memory tip',title:`Memory tip for ${label}`},
  {kind:'comparison',label:'Show a comparison',title:`Compare ${label}`},
  {kind:'common_mistake',label:'Show a common mistake',title:`A common mistake with ${label}`},
].map(item=>({...item,request:aiRequest(request.target,item.kind,item.title,{...request.context,query:request.query})}));let content=items.map(item=>{let draft=assist.get(item.request),primary=draft?`<article class="ai-learning-followup"><span>AI-generated</span><strong>${esc(draft.title)}</strong><p>${esc(draft.body)}</p></article>`:aiLearningSlot(item.request,{compact:true,emptyMessage:`Preparing ${item.label.toLowerCase()}…`}),reference=referenceLearningSlots(request.target,item.kind,item.title,{...request.context,query:request.query},{compact:true});return `${primary}${reference}`}).filter(Boolean).join('');return content?`<div class="ai-learning-more"><h4>Explore further</h4><div class="ai-learning-actions">${content}</div></div>`:''}
function aiLearningSlot(request,{provisional=false,compact=false,emptyMessage='Preparing learning guidance…'}={}){let assist=learningAssist();if(!assist)return '';let draft=assist.get(request),key=autoLearningKey(request);if(draft){let resourceKey=draft.resourceKey||draft.key,expanded=view.aiExpandedResourceKey===resourceKey,shortBody=draft.body.length>340?`${draft.body.slice(0,337).trimEnd()}…`:draft.body,revisions=assist.getRevisions?.(request).length||1,resourceLabel=provisional?'Provisional AI note':`${languageLabel(draft.language||request.language||'en')} AI learning draft`;return `<article class="ai-learning-note ${provisional?'provisional':''}"><div class="ai-learning-note-meta"><span>AI-generated</span><span>${esc(resourceLabel)}</span></div><h3>${esc(draft.title)}</h3><p>${esc(expanded?draft.body:shortBody)}</p>${draft.body.length>340?`<button class="ai-note-expand" data-ai-expand="${esc(resourceKey)}" aria-expanded="${expanded}">${expanded?'Show less':'Read full note'}</button>`:''}${expanded?aiFollowUp(request):`<button class="ai-note-expand" data-ai-expand="${esc(resourceKey)}" aria-expanded="false">Explore further</button>`}<small>${provisional?'This provisional note was generated by AI and may contain mistakes.':'This explanation was generated by AI and may contain mistakes.'}${revisions>1?` ${revisions} local revisions saved.`:''}</small></article>`}if(!aiAssistanceEnabled())return `<div class="ai-learning-unavailable ${compact?'compact':''}"><p>Online learning assistance is off. The local graph remains available.</p></div>`;if(autoLearningFailures.has(key))return `<div class="ai-learning-unavailable ${compact?'compact':''}"><p>${esc(autoLearningFailures.get(key))}</p></div>`;return `<div class="ai-learning-pending ${compact?'compact':''}" data-ai-autofill='${esc(JSON.stringify(aiPayload(request)))}'><p>${esc(emptyMessage)}</p></div>`}
function aiRequestFromPayload(payload){let target=payload.targetId?byId.get(payload.targetId):null;return aiRequest(target,payload.kind,payload.title,{...(payload.context||{}),query:payload.query||''},payload.language||'en')}
const pronunciationForObject=object=>(object.pronunciations||[]).find(record=>record.ipa||record.local_audio_path||record.audio_source_uri)||null;
const pronunciationSource=metadata=>metadata?.source_name||metadata?.provenance||'';
const pronunciationValues=value=>Array.isArray(value)?value:typeof value==='string'?(()=>{try{return JSON.parse(value)}catch{return []}})():[];
const pronunciationNotes=metadata=>[...pronunciationValues(metadata?.liaison_json),...pronunciationValues(metadata?.silent_letters_json),...pronunciationValues(metadata?.elision_json)].filter(Boolean);
const localPath=value=>Boolean(value)&&(/^(?:data:|blob:|\/|\.\/|\.\.\/)/.test(value));
const localRecordingProvider={id:'local-recording',canPlay:metadata=>localPath(metadata?.local_audio_path)||localPath(metadata?.audio_source_uri),play:async({metadata})=>{try{let audio=new Audio(metadata.local_audio_path||metadata.audio_source_uri);await audio.play();return true}catch{return false}}};
const localTtsProvider={id:'local-tts-cache',canPlay:metadata=>localPath(metadata?.local_tts_path),play:async({metadata})=>{try{let audio=new Audio(metadata.local_tts_path);await audio.play();return true}catch{return false}}};
const browserSpeechProvider={id:'browser-speech',canPlay:()=>('speechSynthesis' in window)&&('SpeechSynthesisUtterance' in window),play:({text,locale='fr-FR'})=>{if(!browserSpeechProvider.canPlay())return false;window.speechSynthesis.cancel();let utterance=new SpeechSynthesisUtterance(text);utterance.lang=locale;let voice=window.speechSynthesis.getVoices().find(candidate=>candidate.lang.toLowerCase().startsWith('fr'));if(voice)utterance.voice=voice;window.speechSynthesis.speak(utterance);return true}};
const pronunciationPlayback={providers:[localRecordingProvider,localTtsProvider,browserSpeechProvider],play:async(languageObject,metadata)=>{if(!metadata)return false;let request={languageObject,text:languageObject.canonical_form||languageObject.display_form,locale:metadata.locale||'fr-FR',metadata};for(let provider of pronunciationPlayback.providers)if(provider.canPlay(metadata)&&await provider.play(request))return true;return false}};
const playPronunciation=languageObject=>pronunciationPlayback.play(languageObject,pronunciationForObject(languageObject));
function applyChinesePreference(){let meaning=document.querySelector('.meaning');if(meaning&&meaning.firstChild?.nodeType===3&&!showChinese())meaning.firstChild.textContent=''}
function indexObject(o){if(!o||byId.has(o.id))return;byId.set(o.id,o);let key=o.search_key||norm(o.normalized_form),list=byForm.get(key)||[];list.push(o);byForm.set(key,list);if(o.sense_owner_id)senseOwners.set(o.id,o.sense_owner_id)}
async function hydrateObjects(ids){let hydrated=await graphData.hydrate(ids);hydrated.forEach(indexObject);return hydrated}
async function loadWordbank(){try{graphData=await window.LiensGraphData.load();objects=graphData.objects;objects.forEach(indexObject);engine=new SentenceIntelligence(objects);home()}catch{app.innerHTML='<main class="main"><p class="empty">The local knowledge graph could not load. Serve this folder with a local web server.</p></main>'}}
function queueAutoLearningResources(){let assist=learningAssist(),epoch=renderEpoch,nodes=[...document.querySelectorAll('[data-ai-autofill]')],requests=nodes.map(node=>aiRequestFromPayload(JSON.parse(node.dataset.aiAutofill))),availability=typeof assist?.refreshProviderAvailability==='function'?assist.refreshProviderAvailability():assist?.providerReady?.();if(!assist||!requests.length)return;Promise.resolve(availability).then(ready=>{if(epoch!==renderEpoch)return;if(!ready){requests.forEach(request=>rememberAutoFailure(request,'provider unavailable'));renderTarget({...view,aiRefresh:Date.now()});return}requests.forEach(request=>assist.ensure(request).then(result=>{if(epoch!==renderEpoch)return;if(result?.draft)renderTarget({...view,aiRefresh:Date.now()});else{rememberAutoFailure(request,result?.status);renderTarget({...view,aiRefresh:Date.now()})}}).catch(error=>{if(epoch!==renderEpoch)return;rememberAutoFailure(request,error);renderTarget({...view,aiRefresh:Date.now()})}));}).catch(()=>{});}
function shell(content){renderEpoch+=1;app.innerHTML=`<div class="shell"><header class="top"><button class="brand" data-home>L<i>i</i>ens</button><div class="top-actions"><button class="icon" aria-label="Vocabulary" data-vocab>▤</button><button class="icon" aria-label="Settings" data-settings>⚙</button><button class="icon" aria-label="Home" data-home>⌂</button></div></header><main class="main">${content}</main></div>`;applyChinesePreference();bind();queueAutoLearningResources()}
function home(){view={type:'home'};shell(`<section class="home"><div class="eyebrow">French, in context</div><h1>Every connection is <em>learnable.</em></h1><p class="subtitle">Search the local A1–B2 knowledge graph: words, forms, expressions, and grammar.</p><form class="search" id="search"><input autofocus placeholder="Try: sommes, venir, or avoir besoin de" aria-label="Search French"/><button aria-label="Search">→</button></form><div class="suggestions"><span>Explore</span><button class="chip" data-query="sommes">sommes</button><button class="chip" data-query="venir">venir</button><button class="chip" data-query="avoir besoin de">avoir besoin de</button></div><div class="home-footer">Local knowledge graph · ${objects.filter(o=>o.type_code==='word').length.toLocaleString()} A1–B2 words</div></section>`)}
function formPriority(form){let mood={indicative:0,conditional:1,subjunctive:2,imperative:3,participle:4}[form.features?.mood]??9,tense=form.features?.tense==='present'?0:1;return [mood,tense,form.id]}
function preferredForm(candidates){return candidates.filter(o=>o.type_code==='inflected_form').sort((a,b)=>{let aa=formPriority(a),bb=formPriority(b);return aa[0]-bb[0]||aa[1]-bb[1]||aa[2].localeCompare(bb[2])})[0]}
function resolve(input){let q=norm(input),hits=byForm.get(q)||[],lookup=hits.filter(o=>o.type_code!=='sentence');if(lookup.length){let form=preferredForm(lookup),words=lookup.filter(o=>o.type_code==='word').sort((a,b)=>(b.frequency_per_million||0)-(a.frequency_per_million||0));return routeForObject(form||words[0]||lookup[0])}return q.split(/\s+/).length>1?{type:'sentence',text:input}:{type:'missing',query:input,message:'No local object found. Liens keeps unverified learning material separate from the local graph.'}}
function isSaved(key){return saved.some(x=>x.key===key)}function toggle(item){let i=saved.findIndex(x=>x.key===item.key);if(i>-1)saved.splice(i,1);else saved.unshift(item);persist();render()}
function related(o){return (o.relationships||[]).map(r=>({type:r.type,target:byId.get(r.target)})).filter(x=>x.target)}
function englishGlosses(o){return [...new Set((o.facts||[]).filter(f=>['english_gloss','english_translation'].includes(f.predicate_code)&&f.language_code==='en'&&f.value_text).map(f=>f.value_text))]}
function primaryEnglishGloss(o){return (o?.definitions||[])[0]?.english_gloss||englishGlosses(o||{})[0]||''}
function frenchDefinitions(o){return [...new Set((o.facts||[]).filter(f=>f.predicate_code==='french_definition'&&f.language_code==='fr'&&f.value_text).map(f=>f.value_text))]}
function primaryFrenchDefinition(o){return frenchDefinitions(o||{})[0]||''}
function senseObjects(o){return (o.senses||[]).map(id=>byId.get(id)).filter(Boolean)}
function senseOwner(sense){return sense&&sense.type_code==='lexical_sense'?byId.get(sense.sense_owner_id||senseOwners.get(sense.id)):null}
function routeForObject(object){let owner=senseOwner(object);return owner?{type:'object',id:owner.id,selectedSenseId:object.id}:object?{type:'object',id:object.id}:{type:'home'}}
function featureLabel(features){if(!features)return '';let person=features.person?`person ${features.person}${features.number?` · ${features.number}`:''}`:'';return [features.mood,features.tense,person].filter(Boolean).join(' · ')}
function formOrder(form){let f=form.features||{},number=f.number==='singular'?0:f.number==='plural'?1:2;return [number,Number(f.person||9),form.display_form]}
function compareForms(a,b){let aa=formOrder(a),bb=formOrder(b);return aa[0]-bb[0]||aa[1]-bb[1]||aa[2].localeCompare(bb[2])}
function learnerSubject(form){let f=form.features||{},key=`${f.number||''}:${f.person||''}`;return {'singular:1':'je','singular:2':'tu','singular:3':'il / elle / on','plural:1':'nous','plural:2':'vous','plural:3':'ils / elles'}[key]||'form'}
function realizationOrder(realization){let r=realization.realization||{},number=r.number==='singular'?0:r.number==='plural'?1:2;return [number,Number(r.person||9),realization.display_form]}
function compareRealizations(a,b){let aa=realizationOrder(a),bb=realizationOrder(b);return aa[0]-bb[0]||aa[1]-bb[1]||aa[2].localeCompare(bb[2])}
function realizationSubject(realization){let r=realization.realization||{},key=`${r.number||''}:${r.person||''}`;return {'singular:1':'je','singular:2':'tu','singular:3':'il / elle / on','plural:1':'nous','plural:2':'vous','plural:3':'ils / elles'}[key]||'form'}
function factCode(object,predicate){return (object.facts||[]).find(fact=>fact.predicate_code===predicate)?.value_code||''}
function verbGroupInfo(verb){let code=factCode(verb,'verb_group');return {first_group:{label:'1er groupe',description:'Regular -er verb.'},second_group:{label:'2e groupe',description:'Regular -ir verb with a present participle in -issant.'},third_group:{label:'3e groupe',description:'Third-group verb.'}}[code]||null}
function verbProfileSection(verb){let metadata=verb.verb_metadata;if(verb.type_code!=='word'||!metadata)return '';let auxiliary=metadata.auxiliary_lemma_id?byId.get(metadata.auxiliary_lemma_id):null,explanation=metadata.explanation_object_id?byId.get(metadata.explanation_object_id):null,definition=(explanation?.definitions||[])[0]||{};return `<div class="section verb-profile">${metadata.future_stem||auxiliary?`<h2>Verb profile</h2><div class="facts">${metadata.future_stem?`<span class="fact">future stem ${esc(metadata.future_stem)}</span>`:''}${auxiliary?`<span class="fact">auxiliary ${esc(auxiliary.display_form)}</span>`:''}</div>`:''}</div><div class="section"><h2>How this verb conjugates</h2><p class="section-copy">${esc(definition.explanation_en||'A structured conjugation explanation has not been added yet.')}</p>${chinese(definition.explanation_zh)}</div>`}
function conjugationLearningGroups(lemma){let formIds=graphData?.conjugationFor(lemma.id)||{},groups=graphData?.learningGroups()||[];return groups.map(groupRecord=>{let group=byId.get(groupRecord.id),tenses=(groupRecord.tense_ids||[]).map(id=>byId.get(id)).filter(Boolean).sort((a,b)=>(a.tense_metadata?.display_order||999)-(b.tense_metadata?.display_order||999)).map(tense=>{let forms=(formIds[tense.id]||[]).map(id=>byId.get(id)).filter(Boolean).sort(compareForms);return {tense,forms,realizations:[]}});return {group,tenses}}).filter(group=>group.group&&group.tenses.length)}
function groupIsOpen(group,index,state){return state?.[group.id]??index===0}
function conjugationSection(lemma,selectedTenseId,openGroups){if(lemma.type_code!=='word'||!['VER','V'].includes(lemma.part_of_speech))return '';let groups=conjugationLearningGroups(lemma);if(!groups.length)return '';let verbGroup=verbGroupInfo(lemma),groupTeaching=verbGroup?`<div class="verb-group-teaching"><span>Verb group</span><strong>${esc(verbGroup.label)}</strong><p>${esc(verbGroup.description)}</p></div>`:`<div class="verb-group-teaching unavailable"><span>Verb group</span><strong>Not classified yet</strong><p>Liens will show a group only when local lexical and morphology evidence supports it.</p></div>`,choices=groups.flatMap(group=>group.tenses.map(item=>({...item,group}))),selected=choices.find(choice=>choice.tense.id===selectedTenseId)||choices[0],navigation=groups.map((entry,index)=>{let open=groupIsOpen(entry.group,index,openGroups);return `<div class="learning-group ${open?'open':''}"><button class="learning-group-toggle" data-learning-group="${esc(entry.group.id)}" data-expanded="${open}" aria-expanded="${open}"><span>${open?'▼':'▶'} ${esc(entry.group.display_form)}</span><small>${esc(entry.group.cefr_level||'')}</small></button>${open?`<div class="tense-list">${entry.tenses.map(item=>`<button class="tense-item ${item.tense.id===selected.tense.id?'active':''}" data-tense="${esc(item.tense.id)}" data-tense-group="${esc(entry.group.id)}"><span>${esc(item.tense.display_form)}</span><small>${item.forms.length||item.realizations.length?'':'Not added yet'}</small></button>`).join('')}</div>`:''}</div>`}).join(''),rows=selected.forms.length?selected.forms.map(form=>({id:form.id,subject:learnerSubject(form),surface:form.display_form})):selected.realizations.map(realization=>({id:realization.id,subject:realizationSubject(realization),surface:realization.display_form})),body=rows.length?`<div class="conjugation-table">${rows.map(row=>`<button type="button" class="conjugation-row" data-conjugation-form="${esc(row.id)}"><span>${esc(row.subject)}</span><strong>${esc(row.surface)}</strong></button>`).join('')}</div>`:`<div class="paradigm-empty">This learning target is ready in the knowledge graph. Its forms have not been added to the local bank yet.</div>`;return `<div class="section conjugation-module"><h2>Conjugation</h2>${groupTeaching}<div class="learning-groups">${navigation}</div><h3 class="paradigm-title">${esc(selected.tense.display_form)}</h3><div class="facts tense-facts"><span class="fact">${esc(selected.tense.cefr_level||'')}</span>${selected.tense.tense_metadata?.formation?`<span class="fact">${esc(selected.tense.tense_metadata.formation)}</span>`:''}</div>${body}</div>`}
function exampleCards(ids){return [...new Set(ids||[])].map(id=>byId.get(id)).filter(Boolean).map(example=>`<button class="example" data-sentence="${esc(example.id)}"><div class="fr">${esc(example.display_form)}</div><div class="en">${esc(primaryEnglishGloss(example))}</div></button>`).join('')}
function exampleSection(target,ids,context={}){let cards=exampleCards(ids),resourceContext={...context,knownGraphSummary:context.knownGraphSummary||target.display_form},primary=cards||aiLearningSlot(aiRequest(target,'examples',`Examples for ${target.display_form}`,resourceContext),{compact:true,emptyMessage:'Preparing examples…'}),reference=referenceLearningSlots(target,'examples',`Examples for ${target.display_form}`,resourceContext,{compact:true});return `<div class="sense-detail"><h3>Examples</h3>${primary}${reference}</div>`}
function sensePanel(sense,index,total,expandedExamples){let details=(sense.definitions||[])[0]||{},englishGloss=primaryEnglishGloss(sense),frenchDefinition=primaryFrenchDefinition(sense),gloss=englishGloss||'French source definition',examples=sense.sense_examples||[],visibleExamples=expandedExamples?examples:examples.slice(0,3),links=related(sense).filter(x=>!['has_sense','has_pronunciation'].includes(x.type)),key='object:'+sense.id,context={senseId:sense.id,knownGraphSummary:englishGloss||frenchDefinition||sense.canonical_form},assistance=(!details.explanation_en?aiLearningSlot(aiRequest(sense,'explanation',`Understanding ${sense.canonical_form}`,context),{emptyMessage:'Preparing explanation…'}):'')+referenceLearningSlots(sense,'explanation',`Understanding ${sense.canonical_form}`,context),examplesMarkup=examples.length?`<div class="sense-detail"><h3>Examples</h3>${exampleCards(visibleExamples)}${referenceLearningSlots(sense,'examples',`Examples for ${sense.display_form}`,context,{compact:true})}${examples.length>3?`<button class="sense-more-examples" data-sense-examples="${esc(sense.id)}">${expandedExamples?'Show fewer examples':`Show all ${examples.length} examples`}</button>`:''}</div>`:exampleSection(sense,examples,context);return `<div class="sense-panel" id="sense-panel-${index}" role="region" aria-label="Meaning ${index+1} details"><div class="sense-panel-heading"><span>Meaning ${index+1} of ${total}</span><button class="sense-save ${isSaved(key)?'saved':''}" data-save='${esc(JSON.stringify({key,type:'lexical_sense',id:sense.id,title:`${sense.canonical_form} · ${gloss}`,detail:gloss}))}' aria-label="${isSaved(key)?'Remove':'Save'} this meaning">${isSaved(key)?'Saved meaning':'＋ Save meaning'}</button></div><p class="sense-gloss">${chinese(details.chinese_gloss)}<span>${esc(gloss)}</span></p>${frenchDefinition?`<div class="sense-detail"><h3>French source definition</h3><p class="section-copy">${esc(frenchDefinition)}</p></div>`:''}${details.explanation_en?`<p class="section-copy sense-explanation">${esc(details.explanation_en)}</p>${chinese(details.explanation_zh)}`:''}${assistance}${examplesMarkup}${links.length?`<div class="sense-detail"><h3>Connected knowledge</h3><div class="collocations">${links.map(x=>`<button class="link-card" data-object="${esc(x.target.id)}"><small>${esc(x.type.replace(/_/g,' '))}</small> ${esc(x.target.display_form)} <span>→</span></button>`).join('')}</div></div>`:''}</div>`}
function senseSection(owner,senses,v){let selected=senses.find(sense=>sense.id===v.selectedSenseId)||(v.senseSelectionCleared?null:senses[0]),selectedIndex=selected?senses.findIndex(sense=>sense.id===selected.id):-1,showAll=Boolean(v.showAllSenses)||selectedIndex>=4,visible=showAll?senses:senses.slice(0,4),expandedExamples=selected&&v.expandedSenseExamplesId===selected.id;return `<div class="section sense-module"><div class="sense-module-heading"><div><h2>Meanings</h2><p>${senses.length} source-backed meaning${senses.length===1?'':'s'} · open one when useful</p></div></div><div class="sense-list">${visible.map((sense,index)=>{let absoluteIndex=senses.findIndex(item=>item.id===sense.id),open=sense.id===selected?.id,gloss=primaryEnglishGloss(sense)||'French source definition';return `<article class="sense-entry ${open?'open':''}"><button class="sense-toggle" data-sense-toggle="${esc(sense.id)}" aria-expanded="${open}" aria-controls="sense-panel-${absoluteIndex}"><span class="sense-number">${absoluteIndex+1}</span><span class="sense-label">${esc(gloss)}</span><span class="sense-arrow" aria-hidden="true">${open?'−':'+'}</span></button>${open?sensePanel(sense,absoluteIndex,senses.length,expandedExamples):''}</article>`}).join('')}</div>${senses.length>4?`<button class="sense-show-all" data-show-senses>${showAll?'Show fewer meanings':`Show all ${senses.length} meanings`}</button>`:''}</div>`}
async function objectPage(v){
  let request=++routeEpoch,o=byId.get(v.id);if(!o)return home();let owner=senseOwner(o);if(owner)return objectPage({...v,id:owner.id,selectedSenseId:o.id});view=v;
  await hydrateObjects([o.id]);if(request!==routeEpoch)return;o=byId.get(v.id);
  let senseIds=o.senses||[];if(senseIds.length)await hydrateObjects(senseIds);if(request!==routeEpoch)return;o=byId.get(v.id);
  let selectedSenseId=v.selectedSenseId||(v.senseSelectionCleared?null:senseIds[0]),selectedSense=selectedSenseId?byId.get(selectedSenseId):null,supporting=[...(o.examples||[]),...(selectedSense?.sense_examples||[]).slice(0,3),o.verb_metadata?.explanation_object_id].filter(Boolean);
  if(supporting.length)await hydrateObjects(supporting);if(request!==routeEpoch)return;o=byId.get(v.id);
  let defs=o.definitions||[],d=defs[0]||{},senses=senseObjects(o),sourceFrenchDefinition=primaryFrenchDefinition(senses[0]),definition=primaryEnglishGloss(o)||primaryEnglishGloss(senses[0])||(sourceFrenchDefinition?'French source definition available below.':'No local definition yet.'),pronunciation=pronunciationForObject(o),features=o.features,formOf=related(o).find(x=>x.type==='inflected_form_of'),links=related(o).filter(x=>!['inflected_form_of','member_of_paradigm','belongs_to_conjugation','explains_conjugation','has_pronunciation','has_sense'].includes(x.type)),examples=o.examples||[],key='object:'+o.id,label=o.type_code.replace(/_/g,' ');
  let pronunciationMarkup=pronunciation?.ipa?`${esc(pronunciation.ipa)}<button class="pronounce" data-pronounce="${esc(o.id)}" aria-label="Listen to French pronunciation for ${esc(o.display_form)}" title="Listen to French pronunciation">🔊</button>`:'Pronunciation unavailable',metadata=pronunciation?`<div class="pronunciation-meta">${pronunciationSource(pronunciation)?`<span>Source · ${esc(pronunciationSource(pronunciation))}</span>`:''}${pronunciation.variant_code&&pronunciation.variant_code!=='standard'?`<span>${esc(pronunciation.variant_code)}</span>`:''}${pronunciationNotes(pronunciation).length?`<span>${esc(pronunciationNotes(pronunciation).join(' · '))}</span>`:''}</div>`:'';
  let formRelationship=formOf?`<div class="object-relation"><span>↓ Inflected form of</span><button data-object="${esc(formOf.target.id)}">${esc(formOf.target.display_form)} <b>→</b></button></div>`:'',meaningMarkup=!senses.length?`<p class="meaning">${chinese(d.chinese_gloss)}<span class="definition">${esc(definition)}</span></p>`:'',overviewContext={knownGraphSummary:definition},overviewAssistance=(!d.explanation_en?aiLearningSlot(aiRequest(o,'usage_note',`Learning ${o.display_form}`,overviewContext),{emptyMessage:'Preparing learning guidance…'}):'')+referenceLearningSlots(o,'usage_note',`Learning ${o.display_form}`,overviewContext),wordOverview=`<div class="section word-overview"><h2>Learn in context</h2><p class="section-copy">${esc(d.explanation_en||(o.type_code==='inflected_form'?'This is a distinct Language Object. Its pronunciation and learning content are stored separately from its lemma.':'This core object is resolved locally. A teacher-style explanation can be added as reviewed enrichment without changing its identity.'))}</p>${chinese(d.explanation_zh)}${overviewAssistance}</div>`;
  shell(`<section class="page ${senses.length?'sense-context':''}"><button class="back" data-back>← Back</button><div class="type">${esc(label)}</div><div class="heading-row"><div><h1 class="word-title">${esc(o.display_form)}</h1><div class="pronunciation-row"><p class="phonetic ${pronunciation?.ipa?'':'unavailable'}">${pronunciationMarkup}</p>${metadata}</div></div><button class="save ${isSaved(key)?'saved':''}" data-save='${esc(JSON.stringify({key,type:'object',id:o.id,title:o.display_form,detail:definition||label}))}'>${isSaved(key)?'Saved':'＋ Save'}</button></div>${formRelationship}${meaningMarkup}<div class="facts">${o.cefr_level?`<span class="fact">${o.cefr_level}</span>`:''}${o.part_of_speech?`<span class="fact">${esc(o.part_of_speech)}</span>`:''}${features?`<span class="fact">${esc(featureLabel(features))}</span>`:''}${o.frequency_per_million?`<span class="fact">frequency ${Math.round(o.frequency_per_million)}/m</span>`:''}<span class="fact">${esc(o.content_status)}</span>${d.source_kind==='ai_enriched'?'<span class="fact">AI draft</span>':''}${o.type_code==='inflected_form'&&o.content_status==='ai_enriched'?'<span class="fact">form draft</span>':''}</div>${senses.length?senseSection(o,senses,v):wordOverview}${senses.length?wordOverview:''}${verbProfileSection(o)}${conjugationSection(o,v.selectedTenseId,v.openGroups)}${links.length?`<div class="section"><h2>Connected objects</h2><div class="collocations">${links.map(x=>`<button class="link-card" data-object="${esc(x.target.id)}"><small>${esc(x.type.replace(/_/g,' '))}</small> ${esc(x.target.display_form)} <span>→</span></button>`).join('')}</div></div>`:''}${!senses.length?exampleSection(o,examples):''}<div class="section"><h2>Graph identity</h2><p class="section-copy">${esc(o.id)}</p></div></section>`)
}
function clickable(id,label,classes='token'){return id?`<button class="${classes}" data-object="${esc(id)}">${esc(label)}</button>`:`<span class="${classes}">${esc(label)}</span>`}
function estimateLevel(analysis){let rank={A1:1,A2:2,B1:3,B2:4},levels=analysis.tokens.map(t=>byId.get(t.lemmaId||t.objectId)?.cefr_level).filter(Boolean);return levels.sort((a,b)=>rank[b]-rank[a])[0]||'—'}
function missing(v){view=v;let context={query:v.query},assistance=aiLearningSlot(aiRequest(null,'provisional_lookup',`Learning ${v.query}`,context),{provisional:true,emptyMessage:'Preparing provisional learning guidance…'})+referenceLearningSlots(null,'provisional_lookup',`Learning ${v.query}`,context,{provisional:true});shell(`<section class="page"><button class="back" data-back>← Back</button><div class="type">Local lookup</div><h1 class="sentence-title">${esc(v.query)}</h1><div class="insight"><div class="label">Not in the local bank</div><p>${esc(v.message)}</p></div>${assistance}</section>`)}
function vocabulary(){view={type:'vocab'};shell(`<section class="page"><div class="collection-header"><div class="type">Your learning</div><h1>Vocabulary</h1></div><div class="saved-list">${saved.length?saved.map(x=>`<div class="saved-item"><button data-object="${esc(x.id||'')}"><strong>${esc(x.title)}</strong><span>${esc(x.detail)}</span></button><button class="icon" data-remove="${esc(x.key)}">×</button></div>`).join(''):`<div class="empty">Nothing saved yet. Explore a local object, then keep it for review.</div>`}</div></section>`)}
function settings(aiStatusChecked=false){view={type:'settings',aiStatusChecked};if(!aiStatusChecked)learningAssist()?.refreshProviderAvailability().then(()=>{if(view.type==='settings')settings(true)});let providerStatus=aiProviderReady()?'Online assistance completes missing learning resources, caches them locally, and labels every AI draft. It never modifies the local graph.':'Online assistance is unavailable in this session. Local graph knowledge remains available.';shell(`<section class="page settings-page"><button class="back" data-back>← Back</button><div class="type">Preferences</div><h1 class="sentence-title">Settings</h1><p class="section-copy">English definitions are always shown. Choose whether Liens may use online assistance to fill missing learning guidance.</p><div class="settings-row"><div><h2>Show Chinese</h2><p>Display Chinese reference-language resources when they are locally available or can be prepared by online assistance.</p></div><button class="toggle ${showChinese()?'on':''}" role="switch" aria-checked="${showChinese()}" aria-label="Show Chinese" data-toggle-chinese><span></span></button></div><div class="settings-row"><div><h2>Online learning assistance</h2><p>${esc(providerStatus)}</p></div><button class="toggle ${aiAssistanceEnabled()?'on':''}" role="switch" aria-checked="${aiAssistanceEnabled()}" aria-label="Use online learning assistance" data-toggle-ai><span></span></button></div></section>`)}
function bind(){
  document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>{navigationStack=[];home()});
  document.querySelectorAll('[data-vocab]').forEach(x=>x.onclick=vocabulary);
  document.querySelectorAll('[data-settings]').forEach(x=>x.onclick=()=>settings());
  let form=document.querySelector('#search');if(form)form.onsubmit=e=>{e.preventDefault();go(resolve(form.querySelector('input').value))};
  document.querySelectorAll('[data-query]').forEach(x=>x.onclick=()=>go(resolve(x.dataset.query)));
  document.querySelectorAll('[data-object]').forEach(x=>x.onclick=()=>x.dataset.object&&go(routeForObject(byId.get(x.dataset.object))));
  document.querySelectorAll('[data-sentence]').forEach(x=>x.onclick=()=>{let item=byId.get(x.dataset.sentence);item&&go({type:'sentence',text:item.display_form})});
  document.querySelectorAll('[data-back]').forEach(x=>x.onclick=()=>{let prev=navigationStack.pop();prev?renderTarget(prev):home()});
  document.querySelectorAll('[data-conjugation-form]').forEach(x=>x.onclick=()=>{let form=byId.get(x.dataset.conjugationForm);form&&go({type:'object',id:form.id})});
  document.querySelectorAll('[data-pronounce]').forEach(x=>x.onclick=()=>{let object=byId.get(x.dataset.pronounce);object&&playPronunciation(object)});
  document.querySelectorAll('[data-sense-toggle]').forEach((x,index,items)=>{x.onclick=()=>{let owner=byId.get(view.id),defaultSenseId=!view.senseSelectionCleared?senseObjects(owner)[0]?.id:null,currentSenseId=view.selectedSenseId||defaultSenseId,isCurrent=currentSenseId===x.dataset.senseToggle;renderTarget({...view,selectedSenseId:isCurrent?null:x.dataset.senseToggle,senseSelectionCleared:isCurrent,expandedSenseExamplesId:null})};x.onkeydown=e=>{let target;if(e.key==='ArrowDown')target=items[(index+1)%items.length];if(e.key==='ArrowUp')target=items[(index-1+items.length)%items.length];if(e.key==='Home')target=items[0];if(e.key==='End')target=items[items.length-1];if(target){e.preventDefault();target.focus()}}});
  document.querySelectorAll('[data-show-senses]').forEach(x=>x.onclick=()=>renderTarget({...view,showAllSenses:!view.showAllSenses}));
  document.querySelectorAll('[data-sense-examples]').forEach(x=>x.onclick=()=>renderTarget({...view,expandedSenseExamplesId:view.expandedSenseExamplesId===x.dataset.senseExamples?null:x.dataset.senseExamples}));
  document.querySelectorAll('[data-learning-group]').forEach(x=>x.onclick=()=>{let groups={...(view.openGroups||{}),[x.dataset.learningGroup]:x.dataset.expanded!=='true'};renderTarget({...view,openGroups:groups})});
  document.querySelectorAll('[data-tense]').forEach(x=>x.onclick=()=>renderTarget({...view,selectedTenseId:x.dataset.tense,openGroups:{...(view.openGroups||{}),[x.dataset.tenseGroup]:true}}));
  document.querySelectorAll('[data-save]').forEach(x=>x.onclick=()=>toggle(JSON.parse(x.dataset.save)));
  document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{saved=saved.filter(s=>s.key!==x.dataset.remove);persist();vocabulary()});
  document.querySelectorAll('[data-toggle-chinese]').forEach(x=>x.onclick=()=>{localStorage.setItem('liens-show-chinese',String(!showChinese()));settings()})
  document.querySelectorAll('[data-toggle-ai]').forEach(x=>x.onclick=()=>{learningAssist()?.setEnabled(!aiAssistanceEnabled());settings()});
  document.querySelectorAll('[data-ai-expand]').forEach(x=>x.onclick=()=>renderTarget({...view,aiExpandedResourceKey:view.aiExpandedResourceKey===x.dataset.aiExpand?null:x.dataset.aiExpand}));
  document.querySelectorAll('[data-ai-assist]').forEach(x=>x.onclick=async()=>{let request=aiRequestFromPayload(JSON.parse(x.dataset.aiAssist));x.disabled=true;x.textContent='Preparing learning note…';try{let result=await learningAssist()?.generate(request);if(result?.draft)renderTarget({...view,aiExpandedResourceKey:result.draft.resourceKey||result.draft.key,aiRefresh:Date.now()});else{x.disabled=false;x.textContent=result?.status==='disabled'?'Enable AI assistance in Settings':'AI provider unavailable'}}catch{x.disabled=false;x.textContent='Could not prepare this note'}});
}
function teacherGuide(node){let guide=node.teaching,related=(guide?.relatedIds||[]).map(id=>byId.get(id)).filter(Boolean),target=byId.get(node.objectId),context={knownGraphSummary:node.label},assistance=(!guide&&target?aiLearningSlot(aiRequest(target,'explanation',`Understanding ${node.label}`,context),{emptyMessage:'Preparing grammar guidance…'}):'')+referenceLearningSlots(target,'explanation',`Understanding ${node.label}`,context);return `<article class="teacher-guide"><button class="teacher-guide-title" data-object="${esc(node.objectId||'')}">${esc(node.label)} <span>→</span></button>${guide?`<p><small>Why</small>${esc(guide.why||'')}</p><p><small>How it is formed</small>${esc(guide.formation||'')}</p>${guide.mistakes?.length?`<p><small>Watch out</small>${esc(guide.mistakes.join(' '))}</p>`:''}${related.length?`<div class="collocations">${related.map(item=>clickable(item.id,item.display_form,'link-card grammar-card')).join('')}</div>`:''}`:`<p>This recognised structure is available for exploration in the local knowledge graph.</p>${assistance}`}</article>`}
function sentenceLearningRequest(analysis,language='en'){let summary=[...analysis.grammar.map(node=>node.label),...analysis.expressions.map(node=>node.label)].join(' · ')||'Words resolved locally';return aiRequest(null,'sentence_guide','Understanding this sentence',{query:analysis.sentence,sentence:analysis.sentence,knownGraphSummary:summary},language)}
function sentenceLearningActions(analysis){let request=sentenceLearningRequest(analysis),content=aiLearningSlot(request,{emptyMessage:'Preparing translation and contextual guidance…'})+referenceLearningSlots(null,'sentence_guide','Understanding this sentence',request.context);return content?`<div class="section sentence-ai-assistance"><h2>Learn with this sentence</h2><p class="section-copy">Liens keeps the local analysis visible, then completes missing teaching guidance here.</p><div class="sentence-ai-actions">${content}</div></div>`:''}
function sentencePageIntegrated(v){let a=engine.analyze(v.text,saved.filter(x=>x.id).map(x=>x.id)),evidence=new Map(),localSentence=(byForm.get(norm(a.sentence))||[]).find(item=>item.type_code==='sentence'),sourceTranslation=primaryEnglishGloss(localSentence),sentenceRequest=sentenceLearningRequest(a),sentenceDraft=learningAssist()?.get(sentenceRequest),referenceTranslations=referenceLanguages().map(language=>learningAssist()?.get(sentenceLearningRequest(a,language))?.translation).filter(Boolean),primaryFailure=autoLearningFailures.get(autoLearningKey(sentenceRequest)),fallbackTranslation=primaryFailure?'Translation is temporarily unavailable while online assistance is busy.':aiAssistanceEnabled()?'Preparing translation and contextual guidance…':'Local translation unavailable while online learning assistance is off.';view={...v,analysis:a};[...a.expressions,...a.grammar].forEach(n=>(n.evidence||[]).forEach(i=>{let marks=evidence.get(i)||[];marks.push(n.type==='grammar_construction'?'grammar':'expression');evidence.set(i,marks)}));let unknown=a.unknownTokens.length; shell(`<section class="page sentence-page"><button class="back" data-back>← Back</button><div class="type">Sentence learning</div><h1 class="sentence-title">${esc(a.sentence)}</h1><p class="translation">${esc(sourceTranslation||sentenceDraft?.translation||fallbackTranslation)}${referenceTranslations.map(translation=>chinese(translation)).join('')}</p><div class="insight"><div class="label">Teacher’s guide</div><p>${a.grammar.length?`This sentence uses ${a.grammar.map(n=>esc(n.label)).join(' · ')}. Explore the explanation below, then open any connected object.`:'Liens resolved the words locally and is keeping the sentence ready for exploration.'}</p></div><div class="section"><h2>Sentence breakdown</h2><div class="tokens sentence-tokens">${a.tokens.map((t,i)=>clickable(t.objectId||t.lemmaId,t.surface,`token sentence-token ${(evidence.get(i)||[]).join(' ')}`)).join(' ')}</div>${unknown?`<p class="section-copy">New locally: ${esc(a.unknownTokens.join(', '))}.</p>`:''}</div>${sentenceLearningActions(a)}${a.grammar.length?`<div class="section"><h2>Grammar, explained</h2><div class="teacher-guides">${a.grammar.map(teacherGuide).join('')}</div></div>`:''}${a.expressions.length?`<div class="section"><h2>Useful connections</h2><div class="collocations">${a.expressions.map(n=>clickable(n.objectId,n.label,'link-card expression-card')).join('')}</div></div>`:''}<div class="section"><h2>Learning opportunities</h2><p class="section-copy">${a.learning.reviewCandidateIds.length} objects recognised · ${a.expressions.length} expressions · ${a.grammar.length} learning guides.</p><div class="facts"><span class="fact">${a.learning.newObjectIds.length} new</span><span class="fact">${a.learning.savedObjectIds.length} saved</span><span class="fact">${a.learning.reviewCandidateIds.length} review candidates</span><span class="fact">${estimateLevel(a)}</span></div></div></section>`)}
function render(){if(view.type==='object')objectPage(view);else if(view.type==='sentence')sentencePageIntegrated(view);else if(view.type==='missing')missing(view);else if(view.type==='vocab')vocabulary();else if(view.type==='settings')settings();else home()}
function renderTarget(next){let preserveScroll=view.type==='object'&&next.type==='object'&&view.id===next.id,scrollY=preserveScroll?window.scrollY:0;if(next.type==='object')objectPage(next);else if(next.type==='sentence')sentencePageIntegrated(next);else if(next.type==='settings')settings();else if(next.type==='vocab')vocabulary();else if(next.type==='missing')missing(next);else home();if(preserveScroll)requestAnimationFrame(()=>window.scrollTo(0,scrollY))}
function go(next){if(!next)return;navigationStack.push({...view});renderTarget(next)}
app.innerHTML='<main class="main"><p class="empty">Loading local knowledge graph…</p></main>';loadWordbank();
